"""Change relationship in Posts.images

Revision ID: 037274c7f7ff
Revises: 04e5f2a21e8c
Create Date: 2024-07-23 19:58:40.558716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '037274c7f7ff'
down_revision: Union[str, None] = '04e5f2a21e8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
