"""Fix back_populates param in PostImages

Revision ID: 04e5f2a21e8c
Revises: 185f1eebfcb8
Create Date: 2024-07-23 19:42:50.293910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04e5f2a21e8c'
down_revision: Union[str, None] = '185f1eebfcb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
