"""Add source_id in Groups model

Revision ID: 185f1eebfcb8
Revises: 7065edf7b03e
Create Date: 2024-07-23 19:22:37.783004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '185f1eebfcb8'
down_revision: Union[str, None] = '7065edf7b03e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('source_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'source_id')
    # ### end Alembic commands ###
