"""Replace url with urls in PostImages

Revision ID: 1bbeb728db4c
Revises: 29cf33196abe
Create Date: 2024-08-16 13:03:28.265067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bbeb728db4c'
down_revision: Union[str, None] = '29cf33196abe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_images', sa.Column('urls', sa.JSON(), nullable=True))
    op.drop_column('post_images', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_images', sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('post_images', 'urls')
    # ### end Alembic commands ###
