"""Remove Groups.group_image_id

Revision ID: 1de5b8f1887f
Revises: d0bb27be602c
Create Date: 2024-07-24 18:05:17.224200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1de5b8f1887f'
down_revision: Union[str, None] = 'd0bb27be602c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('groups_group_image_id_fkey', 'groups', type_='foreignkey')
    op.drop_column('groups', 'group_image_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('group_image_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('groups_group_image_id_fkey', 'groups', 'group_images', ['group_image_id'], ['id'])
    # ### end Alembic commands ###
