"""Add GroupImages.group_id, remove Groups.group_image_id

Revision ID: 31db7ace9580
Revises: 5a983352b17c
Create Date: 2024-07-24 17:31:30.290598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31db7ace9580'
down_revision: Union[str, None] = '5a983352b17c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_images', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'group_images', 'groups', ['group_id'], ['id'])
    op.drop_constraint('groups_group_image_id_fkey', 'groups', type_='foreignkey')
    op.drop_column('groups', 'group_image_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('group_image_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('groups_group_image_id_fkey', 'groups', 'group_images', ['group_image_id'], ['id'])
    op.drop_constraint(None, 'group_images', type_='foreignkey')
    op.drop_column('group_images', 'group_id')
    # ### end Alembic commands ###
