"""Add uselist=False to GroupImages

Revision ID: 549caba0a83b
Revises: 31db7ace9580
Create Date: 2024-07-24 17:35:40.428191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '549caba0a83b'
down_revision: Union[str, None] = '31db7ace9580'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
