"""Add Groups.group_image_id, remove GroupImages.group_id

Revision ID: 5a983352b17c
Revises: f9c49437a349
Create Date: 2024-07-24 11:05:57.239619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a983352b17c'
down_revision: Union[str, None] = 'f9c49437a349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('group_images_group_id_fkey', 'group_images', type_='foreignkey')
    op.drop_column('group_images', 'group_id')
    op.add_column('groups', sa.Column('group_image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'groups', 'group_images', ['group_image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'group_image_id')
    op.add_column('group_images', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('group_images_group_id_fkey', 'group_images', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###
