"""Create default date_joined, add field is_adminin Users

Revision ID: a4a7eb4d6249
Revises: f80f31e4f07d
Create Date: 2024-07-27 12:26:24.653587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a4a7eb4d6249'
down_revision: Union[str, None] = 'f80f31e4f07d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.alter_column('users', 'date_joined',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'date_joined',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
