"""Groups linked with users, posts linked with groups

Revision ID: a702ecdf94b7
Revises: c2a99361e4f4
Create Date: 2024-07-29 11:49:57.509273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a702ecdf94b7'
down_revision: Union[str, None] = 'c2a99361e4f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'groups', 'users', ['user_id'], ['id'])
    op.drop_constraint('posts_group_id_fkey', 'posts', type_='foreignkey')
    op.drop_column('posts', 'group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('posts_group_id_fkey', 'posts', 'groups', ['group_id'], ['id'])
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'user_id')
    # ### end Alembic commands ###
