"""Add cascades to group, post, image relationships

Revision ID: b5f7a4a4f016
Revises: 2fe69450d31c
Create Date: 2024-07-30 10:39:20.868046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5f7a4a4f016'
down_revision: Union[str, None] = '2fe69450d31c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
