"""Add GroupImages.group_id

Revision ID: d0bb27be602c
Revises: 549caba0a83b
Create Date: 2024-07-24 18:03:33.028732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0bb27be602c'
down_revision: Union[str, None] = '549caba0a83b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('group_image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'groups', 'group_images', ['group_image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'group_image_id')
    # ### end Alembic commands ###
