"""Add vk_id to Posts model

Revision ID: d4749947c383
Revises: 7099422932c3
Create Date: 2024-07-25 00:23:09.148078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4749947c383'
down_revision: Union[str, None] = '7099422932c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('vk_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'vk_id')
    # ### end Alembic commands ###
